# Demo Platform Support
snd-soc-demop-i2s-objs := demop-i2s.o

obj-$(CONFIG_SND_DEMOP_I2S) += snd-soc-demop-i2s.o

# Demo Machine Support
snd-soc-demop-democ-objs := demop-democ.o

obj-$(CONFIG_SND_SOC_DEMOP_DEMOC) += snd-soc-demop-democ.o

# Demo Codec Support
snd-soc-democ-objs := democ.o

obj-$(CONFIG_SND_SOC_DEMOC) += snd-soc-democ.o
